spring:
  application:
    name: smart-display
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      enabled: true
      file: docker-compose.local.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true


integration:
  ujin:
    access-token: ${UJIN_TOKEN:}